'use client'
import { useState, useEffect } from 'react'
import { 
  TrendingUp, Eye, Clock, Users, RefreshCw, 
  ArrowLeft, ThumbsUp, MessageCircle, Languages,
  Play, AlertCircle, Video, BarChart3, Activity, Calendar,
  Globe, MapPin, UserCircle, Subtitles, Monitor, Smartphone
} from 'lucide-react'
import { 
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip, 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Legend,
  LineChart, Line, AreaChart, Area
} from 'recharts'

const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#14b8a6']

const formatNumber = (num) => {
  if (!num) return '0'
  if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M'
  if (num >= 1000) return (num / 1000).toFixed(1) + 'K'
  return num.toString()
}

export default function PublicVideoAnalyticsPage() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [refreshing, setRefreshing] = useState(false)

  const videoId = typeof window !== 'undefined' 
    ? window.location.pathname.split('/').pop() 
    : null

  const fetchAnalytics = async () => {
    try {
      setLoading(true)
      setError(null)
      const response = await fetch(`/api/analytics/video/${videoId}`)
      const result = await response.json()
      console.log('Fetched analytics:', result)
      
      if (!result.success) {
        setError(result.error || 'Failed to fetch analytics')
      } else {
        setData(result)
      }
    } catch (err) {
      setError('Network error. Please try again.')
    } finally {
      setLoading(false)
      setRefreshing(false)
    }
  }

  useEffect(() => {
    if (videoId) {
      fetchAnalytics()
    }
  }, [videoId])

  const handleRefresh = () => {
    setRefreshing(true)
    fetchAnalytics()
  }

  const handleBack = () => {
    if (typeof window !== 'undefined') {
      window.history.back()
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-6">
        <div className="max-w-[1600px] mx-auto">
          <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-16 text-center">
            <div className="w-16 h-16 border-4 border-gray-200 border-t-gray-900 rounded-full animate-spin mx-auto mb-4" />
            <p className="text-gray-600 font-medium">Loading analytics...</p>
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-6">
        <div className="max-w-[1600px] mx-auto space-y-6">
          <button
            onClick={handleBack}
            className="flex items-center gap-2 px-4 py-2 bg-white rounded-xl shadow-md hover:shadow-lg transition-all duration-300 text-gray-700 hover:text-gray-900 font-medium"
          >
            <ArrowLeft size={20} />
            Back to Videos
          </button>
          
          <div className="bg-white rounded-2xl shadow-lg border border-red-200 p-12 text-center">
            <AlertCircle size={64} className="mx-auto text-red-500 mb-4" />
            <h2 className="text-2xl font-bold text-red-900 mb-2">Analytics Unavailable</h2>
            <p className="text-red-700">{error}</p>
          </div>
        </div>
      </div>
    )
  }

  const { video, analytics, trafficSources, subtitles, currentStats } = data

  // Prepare traffic sources for pie chart
  const trafficChartData = trafficSources.map((source, idx) => ({
    name: source.source.replace(/_/g, ' '),
    value: source.views,
    color: COLORS[idx % COLORS.length]
  }))

  // Prepare subtitle language data (top 10)
  const subtitleLanguageData = subtitles.languages
    .slice(0, 10)
    .map((lang, idx) => ({
      code: lang.code,
      name: lang.name || lang.code.toUpperCase(),
      type: lang.isAutoGenerated ? 'Auto' : 'Manual',
      color: COLORS[idx % COLORS.length]
    }))

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-6">
      <div className="max-w-[1600px] mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-start justify-between">
          <div className="flex items-start gap-4">
            <button
              onClick={handleBack}
              className="mt-1 p-3 bg-white rounded-xl shadow-md hover:shadow-lg transition-all duration-300 text-gray-700 hover:text-gray-900"
            >
              <ArrowLeft size={20} />
            </button>
            <div>
              <h1 className="text-4xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 bg-clip-text text-transparent">
                Video Analytics Dashboard
              </h1>
              <p className="text-gray-600 mt-2 line-clamp-1">{video.title}</p>
            </div>
          </div>
          
          <button
            onClick={handleRefresh}
            disabled={refreshing}
            className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-gray-900 to-gray-700 hover:from-gray-800 hover:to-gray-600 text-white rounded-xl transition-all duration-300 transform hover:scale-[1.02] shadow-lg hover:shadow-xl disabled:opacity-50 font-medium"
          >
            <RefreshCw size={20} className={refreshing ? 'animate-spin' : ''} />
            {refreshing ? 'Refreshing...' : 'Refresh Data'}
          </button>
        </div>

        {/* Video Preview */}
        {video.thumbnailUrl && (
          <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-6 overflow-hidden">
            <div className="flex flex-col md:flex-row gap-6">
              <a 
                href={`https://youtube.com/watch?v=${video.videoId}`}
                target="_blank"
                rel="noopener noreferrer"
                className="relative group flex-shrink-0"
              >
                <div className="w-full md:w-80 aspect-video bg-gray-100 rounded-xl overflow-hidden">
                  <img
                    src={video.thumbnailUrl}
                    alt={video.title}
                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                  />
                  
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center rounded-xl">
                    <div className="w-16 h-16 rounded-full bg-white/90 flex items-center justify-center transform scale-90 group-hover:scale-100 transition-transform shadow-2xl">
                      <Play size={28} className="text-gray-900 ml-1" fill="currentColor" />
                    </div>
                  </div>
                </div>
              </a>
              
              <div className="flex-1 flex flex-col justify-center">
                <h2 className="font-bold text-xl mb-3 text-gray-900">{video.title}</h2>
                <div className="flex flex-wrap gap-4 text-sm text-gray-600 mb-4">
                  <div className="flex items-center gap-2">
                    <Video size={16} className="text-gray-400" />
                    <span>ID: {video.videoId}</span>
                  </div>
                  <span className="text-gray-300">•</span>
                  <div className="flex items-center gap-2">
                    <Calendar size={16} className="text-gray-400" />
                    <span>Published: {new Date(video.publishedAt).toLocaleDateString()}</span>
                  </div>
                </div>
                <a
                  href={`https://youtube.com/watch?v=${video.videoId}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center justify-center gap-2 px-6 py-3 bg-red-600 hover:bg-red-700 text-white rounded-xl transition-all duration-300 transform hover:scale-[1.02] shadow-lg hover:shadow-xl font-medium w-fit"
                >
                  <Play size={18} />
                  Watch on YouTube
                </a>
              </div>
            </div>
          </div>
        )}

        {/* Current Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <StatCard
            label="Total Views"
            value={formatNumber(currentStats.views)}
            icon={Eye}
            gradient="from-blue-500 to-blue-600"
            delay={0}
          />
          <StatCard
            label="Likes"
            value={formatNumber(currentStats.likes)}
            icon={ThumbsUp}
            gradient="from-green-500 to-green-600"
            delay={0.1}
          />
          <StatCard
            label="Comments"
            value={formatNumber(currentStats.comments)}
            icon={MessageCircle}
            gradient="from-purple-500 to-purple-600"
            delay={0.2}
          />
          <StatCard
            label="Subtitles"
            value={`${subtitles.count}`}
            icon={Languages}
            gradient="from-orange-500 to-orange-600"
            delay={0.3}
          />
        </div>

        {/* Analytics Metrics */}
        <div className="grid md:grid-cols-2 gap-6">
          {/* Performance Metrics */}
          <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-6">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-3 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl">
                <Activity size={24} className="text-white" />
              </div>
              <h3 className="text-xl font-bold text-gray-900">Performance Metrics</h3>
            </div>
            <div className="space-y-3">
              <MetricRow
                label="Watch Time"
                value={`${formatNumber(analytics.estimatedMinutesWatched)} min`}
                icon={Clock}
              />
              <MetricRow
                label="Avg View Duration"
                value={`${Math.round(analytics.averageViewDuration)} sec`}
                icon={Clock}
              />
              <MetricRow
                label="Avg View Percentage"
                value={`${Math.round(analytics.averageViewPercentage)}%`}
                icon={TrendingUp}
              />
              <MetricRow
                label="Subscribers Gained"
                value={formatNumber(analytics.subscribersGained)}
                icon={Users}
              />
            </div>
          </div>

          {/* Traffic Sources Pie Chart */}
          <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-6">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-3 bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl">
                <BarChart3 size={24} className="text-white" />
              </div>
              <h3 className="text-xl font-bold text-gray-900">Traffic Sources</h3>
            </div>
            {trafficSources.length > 0 ? (
              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={trafficChartData}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
                      outerRadius={80}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {trafficChartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            ) : (
              <div className="py-12 text-center">
                <BarChart3 size={48} className="mx-auto text-gray-300 mb-3" />
                <p className="text-gray-500">No traffic data available</p>
              </div>
            )}
          </div>
        </div>

        {/* Subtitle Languages Section */}
        <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-6">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-gradient-to-br from-orange-500 to-orange-600 rounded-xl">
              <Subtitles size={24} className="text-white" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-gray-900">Subtitle Languages</h3>
              <p className="text-sm text-gray-500">Top 10 available languages (Total: {subtitles.count})</p>
            </div>
          </div>
          
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
            {subtitleLanguageData.map((lang, idx) => (
              <div 
                key={idx}
                className="flex items-center gap-3 p-3 bg-gradient-to-r from-gray-50 to-gray-100 rounded-xl hover:from-gray-100 hover:to-gray-50 transition-all duration-300"
              >
                <div 
                  className="w-3 h-3 rounded-full flex-shrink-0"
                  style={{ backgroundColor: lang.color }}
                />
                <div className="flex-1 min-w-0">
                  <p className="font-bold text-gray-900 text-sm truncate">{lang.code.toUpperCase()}</p>
                  <p className="text-xs text-gray-500">{lang.type}</p>
                </div>
              </div>
            ))}
          </div>

          {subtitles.count > 10 && (
            <div className="mt-4 p-3 bg-blue-50 rounded-xl text-center">
              <p className="text-sm text-blue-700 font-medium">
                +{subtitles.count - 10} more languages available
              </p>
            </div>
          )}
        </div>

        {/* Data Request Section */}
        <div className="bg-gradient-to-br from-yellow-50 to-orange-50 rounded-2xl shadow-lg border-2 border-yellow-200 p-8">
          <div className="flex items-start gap-4">
            <div className="p-4 bg-yellow-500 rounded-2xl flex-shrink-0">
              <AlertCircle size={32} className="text-white" />
            </div>
            <div className="flex-1">
              <h3 className="text-2xl font-bold text-gray-900 mb-3">Need More Analytics Data?</h3>
              <p className="text-gray-700 mb-4 leading-relaxed">
                To display comprehensive analytics including geographic data (countries, states), demographic information (age groups, gender), device types, and subtitle usage statistics, your API needs to provide this additional data from YouTube Analytics API.
              </p>
              
              <div className="grid md:grid-cols-2 gap-4 mb-6">
                <div className="bg-white rounded-xl p-4 border border-yellow-200">
                  <div className="flex items-center gap-3 mb-2">
                    <Globe className="text-blue-600" size={20} />
                    <h4 className="font-bold text-gray-900">Geographic Data</h4>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-1">
                    <li>• Views by country</li>
                    <li>• Views by state/region</li>
                    <li>• Top cities</li>
                  </ul>
                </div>

                <div className="bg-white rounded-xl p-4 border border-yellow-200">
                  <div className="flex items-center gap-3 mb-2">
                    <UserCircle className="text-purple-600" size={20} />
                    <h4 className="font-bold text-gray-900">Demographics</h4>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-1">
                    <li>• Age group breakdown</li>
                    <li>• Gender distribution</li>
                    <li>• Viewer interests</li>
                  </ul>
                </div>

                <div className="bg-white rounded-xl p-4 border border-yellow-200">
                  <div className="flex items-center gap-3 mb-2">
                    <Monitor className="text-green-600" size={20} />
                    <h4 className="font-bold text-gray-900">Device & Playback</h4>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-1">
                    <li>• Device type (mobile, desktop, TV)</li>
                    <li>• Operating systems</li>
                    <li>• Playback locations</li>
                  </ul>
                </div>

                <div className="bg-white rounded-xl p-4 border border-yellow-200">
                  <div className="flex items-center gap-3 mb-2">
                    <Languages className="text-orange-600" size={20} />
                    <h4 className="font-bold text-gray-900">Subtitle Usage</h4>
                  </div>
                  <ul className="text-sm text-gray-600 space-y-1">
                    <li>• Most used subtitle languages</li>
                    <li>• Subtitle views percentage</li>
                    <li>• Language preferences</li>
                  </ul>
                </div>
              </div>

              <div className="bg-yellow-100 border-l-4 border-yellow-500 p-4 rounded-lg">
                <p className="text-sm text-yellow-900 font-medium">
                  <strong>Note:</strong> YouTube Analytics API requires proper OAuth2 authentication and may have quota limits. Update your backend API endpoint <code className="bg-yellow-200 px-2 py-1 rounded text-xs">/api/analytics/video/:id</code> to fetch and return this additional data.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Traffic Sources Table */}
        {trafficSources.length > 0 && (
          <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-6">
            <h3 className="text-xl font-bold text-gray-900 mb-6">Traffic Breakdown</h3>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b-2 border-gray-200">
                    <th className="text-left p-4 font-bold text-gray-700">Source</th>
                    <th className="text-right p-4 font-bold text-gray-700">Views</th>
                    <th className="text-right p-4 font-bold text-gray-700">Percentage</th>
                  </tr>
                </thead>
                <tbody>
                  {trafficSources.map((source, idx) => {
                    const totalViews = trafficSources.reduce((sum, s) => sum + s.views, 0)
                    const percentage = totalViews > 0 ? ((source.views / totalViews) * 100).toFixed(1) : '0.0'
                    return (
                      <tr key={idx} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                        <td className="p-4 font-medium text-gray-900">{source.source.replace(/_/g, ' ')}</td>
                        <td className="p-4 text-right text-gray-700">{formatNumber(source.views)}</td>
                        <td className="p-4 text-right">
                          <span className="inline-block px-3 py-1 bg-blue-50 text-blue-700 rounded-full font-medium">
                            {percentage}%
                          </span>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Data Timestamp */}
        <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-6 text-center">
          <p className="text-sm text-gray-500">
            <span className="font-medium text-gray-700">Last updated:</span> {new Date(data.fetchedAt).toLocaleString()}
          </p>
        </div>
      </div>
    </div>
  )
}

function StatCard({ label, value, icon: Icon, gradient, delay }) {
  const [isVisible, setIsVisible] = useState(false)

  useEffect(() => {
    const timer = setTimeout(() => setIsVisible(true), delay * 1000)
    return () => clearTimeout(timer)
  }, [delay])

  return (
    <div 
      className={`relative rounded-2xl p-6 shadow-lg overflow-hidden transform transition-all duration-500 ${
        isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'
      }`}
    >
      <div className={`absolute inset-0 bg-gradient-to-br ${gradient} opacity-90`} />
      <div className="absolute inset-0 bg-gradient-to-br from-white/20 to-transparent opacity-0 hover:opacity-100 transition-opacity duration-500" />
      
      <div className="relative">
        <div className="flex items-start justify-between mb-3">
          <Icon size={24} className="text-white/80" />
          <div className="w-2 h-2 rounded-full bg-white/50 animate-pulse" />
        </div>
        <p className="text-3xl font-bold text-white mb-1">{value}</p>
        <p className="text-sm text-white/80 font-medium">{label}</p>
      </div>
    </div>
  )
}

function MetricRow({ label, value, icon: Icon }) {
  return (
    <div className="flex items-center justify-between p-4 bg-gradient-to-r from-gray-50 to-gray-100 rounded-xl hover:from-gray-100 hover:to-gray-50 transition-all duration-300">
      <div className="flex items-center gap-3">
        <div className="p-2 bg-white rounded-lg shadow-sm">
          <Icon size={18} className="text-gray-600" />
        </div>
        <span className="text-sm font-medium text-gray-700">{label}</span>
      </div>
      <span className="text-lg font-bold text-gray-900">{value}</span>
    </div>
  )
}