// src/models/Video.js
import mongoose from 'mongoose'

const VideoSchema = new mongoose.Schema(
  {
    // YouTube Data (Auto-fetched)
    videoId: {
      type: String,
      required: [true, 'Video ID is required'],
      unique: true,
      trim: true,
    },
    
    subtitles: {
      count: { type: Number, default: 0 },
      languages: [{ 
        code: String,
        name: String,
        isAutoGenerated: Boolean,
        addedAt: Date
      }],
      lastSynced: Date
    },
    
    analytics: {
      views: Number,
      watchTime: Number,
      avgViewDuration: Number,
      avgViewPercentage: Number,
      subscribersGained: Number,
      trafficSources: [{
        source: String,
        views: Number
      }],
      lastFetched: Date
    },
    
    title: {
      type: String,
      required: [true, 'Title is required'],
    },
    description: {
      type: String,
    },
    thumbnailUrl: {
      type: String,
    },
    duration: {
      type: String,
    },
    publishedAt: {
      type: Date,
    },
    
    // Relationships
    channel: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Channel',
      required: [true, 'Channel is required'],
    },
    series: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Series',
      required: [true, 'Series is required'],
    },
    
    // YouTube Statistics (Auto-fetched & Updated)
    viewCount: {
      type: Number,
      default: 0,
    },
    likeCount: {
      type: Number,
      default: 0,
    },
    commentCount: {
      type: Number,
      default: 0,
    },
    
    subtitleCount: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },
    
    // YouTube Video Status
    privacyStatus: {
      type: String,
      enum: ['public', 'private', 'unlisted'],
      default: 'public',
    },
    uploadStatus: {
      type: String,
      enum: ['uploaded', 'processed', 'failed', 'rejected', 'deleted'],
      default: 'processed',
    },
    
    adStatus: {
      type: String,
      enum: ['running', 'stopped', 'pending', 'not-set'],
      default: 'not-set',
    },
    seoNotes: {
      type: String,
    },
    
    // Upload Tracking
    expectedUploadDate: {
      type: Date,
    },
    status: {
      type: String,
      enum: ['scheduled', 'uploaded', 'delayed'],
      default: 'uploaded',
    },
    
    // Tracking
    lastSyncedAt: {
      type: Date,
      default: Date.now,
    },
    addedBy: {
      type: String,
      default: 'Admin',
    },
  },
  {
    timestamps: true,
  }
)

// Index for faster queries
VideoSchema.index({ videoId: 1 })
VideoSchema.index({ channel: 1, series: 1 })
VideoSchema.index({ status: 1 })
VideoSchema.index({ publishedAt: -1 })
VideoSchema.index({ privacyStatus: 1 })

export default mongoose.models.Video || mongoose.model('Video', VideoSchema)